### PR TITLE
[UI] Add fix for phase change filter when 0

### LINKED ISSUE #247: Filters do not apply correctly/at all when viewing sources of items
**Describe the bug**
When selecting sources of items to filter, the filters do nothing

**To Reproduce**
1. Click on any item, e.g., helmet
2. Click filters
3. Mark/unmark sources as needed

**Expected behavior**
The underlying list of items should be filtered based on your selected sources, but they're not

**Sim Links and Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, tested in Firefox as well
 - Version: Unsure

### PR DESCRIPTION
**Pull request by 1337LutZ**
Partially fixes #247 
- Pre-patch is phase 0, thus the `> 0` check had to be removed
- Other filters don't work since `sources` is populated by AtlasLootClassic and there's no Cataclysm dataset yet.

### CODE REVIEW

**Comment by rosenrusinov** [comment]
We dont support pre-patch and never will in the backend so enabling it on the front end will only confuse users

**Comment by 1337LutZ** [comment]
> We dont support pre-patch and never will in the backend so enabling it on the front end will only confuse users

Hmm, but the item filter is there, but just broken. Or should I just remove it instead?
image

**Comment by rosenrusinov** [comment]
I think we're better off with removing the prepatch filter yes. It wont work anyway as the characters simmed will still be 85

**Comment by 1337LutZ** [comment]
> I think we're better off with removing the prepatch filter yes. It wont work anyway as the characters simmed will still be 85

Resolved 👍

**Pull request merged**
