### PR TITLE
fix warrior rend ticking and "snapshot" behavior

### PR DESCRIPTION
**Pull request by zoristaken**
rend ticking on mortal strike/thunder clap refreshes was fixed with the new patch.

old:
image

new:
image
image

### CODE REVIEW

**Comment by zoristaken** [comment]
there might be some snapshot rolling over like wotlk corruption for aff lock going on, needs more tests

**Comment by zoristaken** [comment]
> there might be some snapshot rolling over like wotlk corruption for aff lock going on, needs more tests

better example:
https://classic.warcraftlogs.com/reports/7GhKxnLt6R3gXNkD#fight=6&type=damage-done&source=1&pins=2%24Off%24%23244F4B%24expression%24ability.name%20in%20(%22Mortal%20Strike%22,%20%22Thunder%20Clap%22,%20%22Rend%22)&view=events

1. normal rend without procs (2340)
2. popped angerforge + potion, kept refreshing with mortal strike still same damage
3. rend recast at 51 seconds, new baseline damage (3535)
4. kept refreshing with mortal strike until the end, damage didn't change

thunder clap:
https://classic.warcraftlogs.com/reports/J4kaGQFYBy28rPK3#fight=7&view=events&type=damage-done&source=1&pins=2%24Off%24%23244F4B%24expression%24ability.name%20in%20(%22Thunder%20Clap%22,%20%22Rend%22)
1. normal rend on target 1 with snapshot (3557)
2. thunder clap refreshes on target 1, but doesn't update value, just like mortal strike refresh
3. thunder clap applies rend to target 2, with new value according to current stats

**Comment by zoristaken** [comment]
@Tharre I added the dot behavior I described on discord, would like your review on this. We can hold on the merge if we can get some confirmation it's intended

**Comment by zoristaken** [comment]
https://www.youtube.com/watch?v=2yYrZqDSLig rend is dynamically updating, can see that at 44 seconds rend ticks for 5229 with potion up, and then at 56 seconds without potion up it does 4844. Mortal strike being the only ability refreshing rend

**Review by Tharre — APPROVED** [review]
LGTM

**Pull request merged**
