### PR TITLE
[Balance] Enable mastery snapshotting + Innervate

### PR DESCRIPTION
**Pull request by koflem**
Ability to start in solar eclipse
Ability to specify a mastery amount for the initial solar eclipse
Enable self innervate (some stuff about innervate target didn't seem to be working so it's just innervate self for now, not like there's much of a reason to innervate someone else anymore...)

### CODE REVIEW

**Review by rosenrusinov — CHANGES_REQUESTED** [review]
- Innervate should support setting external target for raid sim.
- This mastery snapshot is never cleared so every iteration you keep the snapshot mastery for the hole run

**Comment by koflem** [comment]
> * Innervate should support setting external target for raid sim.
Okay, I've never used raid sim so I would have no idea how to test it. I can put back some of the old code and hope it works but given it didn't work before that seems dubious. I guess I'll check out how to raid sim...
>  * This mastery snapshot is never cleared so every iteration you keep the snapshot mastery for the hole run
That's not true, it is cleared.

**Comment by koflem** [comment]
The raid sim isn't even enabled yet for cata... I added back some of the code that would allow a buff target so it *should* work but I have no idea if it does.
Well, it's not like it worked before anyways.

**Comment by koflem** [comment]
It seems like there's an issue in raid sims where only the initial simulation works, any other simulation will break until you refresh. Knowing this, I was able to innervate a mage in raid sim mode so it should be good.

**Comment by koflem** [comment]
Even on the deployed master raid sims I can't get anyone to deal damage (well the tank does like 1k) on any simulations after the first one after a refresh. But like I said I tested it and it did properly innervate the target in the raid sim. One issue is the current APL for balance only uses major cooldowns at 100 lunar energy so the innervate might not be timed properly but that's an APL issue.

**Review by rosenrusinov — APPROVED** [review]

**Comment by stn-ms** [comment]
I would much rather have the option to start at whatever energy level, instead of just forcing Solar. If tomorrow someone figures out that there's merit to starting in Lunar, we would have to do that too.

**Pull request merged**
